XRDDEV-1664
nordic-institute/X-Road pull request #1035
Opened 2021-09-06 10:03 UTC by jhyoty

Move messagelog archiving to a separate process

2021-09-10 10:41 UTC, iluwatar requested changes
Looks good, some minor improvements requested.

2021-09-10 10:41 UTC, iluwatar commented on src/addons/messagelog/messagelog-db/src/main/java/ee/ria/xroad/messagelog/database/MessageRecordEncryption.java
> +public final class MessageRecordEncryption {
Would be good to create a basic Javadoc explaining what this class does. I'm not sure why Checkstyle is not complaining about it.

2021-09-10 11:12 UTC, jhyoty commented on src/addons/messagelog/messagelog-addon/build.gradle
> +    archiveVersion = ''
Seems to work anyway (gradle does not complain) so maybe this is some IDEA issue.

2021-09-14 11:47 UTC, iluwatar approved these changes

2021-09-14 11:48 UTC, merged