XRDDEV-1773 security server views
nordic-institute/X-Road pull request #1062
Opened 2021-09-29 13:39 UTC by Riippi

2021-10-01 09:47 UTC, carohauta requested changes

2021-10-04 14:28 UTC, Riippi commented on src/centralserver/admin-ui/src/views/SecurityServers/SecurityServersList.vue
> +  <sub-view-container>
Fixed

2021-10-04 14:28 UTC, Riippi commented on src/centralserver/admin-ui/src/views/SecurityServers/SecurityServer/SecurityServerClients.vue
> +      <xrd-search v-model="search" />
This was discussed in slack and decided to add search. 
Margin is now fixed.

2021-10-04 14:30 UTC, Riippi commented on src/centralserver/admin-ui/src/views/SecurityServers/SecurityServer/SecurityServer.vue
> +      >
Fixed

2021-10-05 07:37 UTC, carohauta approved these changes
🦄

2021-10-05 07:38 UTC, merged