XRDDEV-1793
nordic-institute/X-Road pull request #1081
Opened 2021-10-28 09:22 UTC by iluwatar

2021-11-01 10:27 UTC, teemukin65 requested changes

2021-11-01 10:27 UTC, teemukin65 commented on src/centralserver/admin-ui/src/store/modules/user.ts
> +        commit(StoreTypes.mutations.SET_SYSTEM_STATUS, resp.data),
I abstract the difference between purposes of the endpoints  systemstatus & initialization/status to be so, that systemstatus returns information set up before the initialization. 
--> initialization status should not be obtained from systemStatus endpoint.  Changes to backend recommended.

This makes the meaning of the endpoints more clear. , easier to maintain & understand. 

The stores should be arranged same way. Actually the system status  & version should be separated out of the user.ts to a new store, e.g. system.ts to make the concepts more clear.

This naturally leads to the situation that the status row component needs to query both system store for ha-status
and initialization for initialization status but I think that is OK.

2021-11-02 09:55 UTC, iluwatar commented on src/centralserver/admin-ui/src/store/modules/user.ts
> +        throw error;
Ok, removed in https://github.com/nordic-institute/X-Road/pull/1081/commits/d3abded92488a348d01019e3c376373889cdd1be

2021-11-02 09:56 UTC, iluwatar commented on src/centralserver/admin-ui/src/store/modules/user.ts
> +        commit(StoreTypes.mutations.SET_SYSTEM_STATUS, resp.data),
Created a new system store and moved system status and version query there. See commit https://github.com/nordic-institute/X-Road/pull/1081/commits/d3abded92488a348d01019e3c376373889cdd1be

2021-11-02 10:24 UTC, merged