XRDDEV-126
nordic-institute/X-Road pull request #1145
Opened 2022-01-04 06:16 UTC by jhyoty

2022-01-17 12:37 UTC, jansu76 requested changes
The getAuthKey optimization seems to be a close call, on whether it is justified. As I understand, the performance benefits are real, but quite small (3% - maybe 6% best case?). As a price for that, they add some amount of complexity to the overall solution. The code changes related to getAuthKey improvements are themselves relatively small and straightforward, but they do add some complexity that people working with key caching and ocsp freshness etc need to understand.

Description at https://confluence.niis.org/pages/viewpage.action?pageId=84837614 sounds correct, but I don't understand all they mechanisms that relate to key validation well enough to validate that the change does not cause any side effects somewhere (sort of related to the previous chapter - the whole is already so complex that I feel timid about adding any new complexity).

2022-01-17 12:37 UTC, jansu76 commented on src/proxy/src/main/java/ee/ria/xroad/proxy/conf/CachingKeyConfImpl.java
> +    /* Implementation note:
:+1: nice to have this kind of implementation notes

2022-01-17 13:11 UTC, jhyoty commented on src/proxy/src/main/java/ee/ria/xroad/proxy/conf/CachingKeyConfImpl.java
> +            final SingleResp singleResp = ((BasicOCSPResp) resp.getResponseObject()).getResponses()[0];
One could request OCSP responses for multiple certificates using just one request (--> multiple responses), but X-Road does not do that.

2022-01-17 13:22 UTC, jhyoty commented on src/proxy/src/main/java/ee/ria/xroad/proxy/conf/CachingKeyConfImpl.java
> +            final Date tmp = new Date(singleResp.getThisUpdate().getTime() + freshnessMillis);
Perhaps, but given the very narrow context it is used in, I think this is readable enough.

2022-01-18 07:15 UTC, jansu76 approved these changes

2022-01-27 13:13 UTC, merged