XRDDEV-1907 configuration loading and caching refactor
nordic-institute/X-Road pull request #1175
Opened 2022-01-30 19:10 UTC by amoog

removed synchronized methods and added configuration background loading. Conf validity is now checked using actual expiration time.

2022-01-31 11:04 UTC, jhyoty requested changes
There seems to be a build failure in GlobalConfTest

2022-02-10 10:49 UTC, jhyoty requested changes

2022-02-10 17:26 UTC, amoog commented on src/common-util/src/main/java/ee/ria/xroad/common/conf/globalconf/SharedParametersV2.java
> +        initCompleted = true;
Code structure is a bit unfortunate - this constructor is used only for checking downloaded SharedParameters, check in reality checks only instanceid, so filling "cache" is completely unnecessary. Then again having such a constructor that "half initialises object is also a possible trap for future developers. I added a comment to constructor which has package level visibility for the reasons above.

2022-02-11 11:06 UTC, jhyoty approved these changes

2022-02-11 11:06 UTC, merged