New cs modularization
nordic-institute/X-Road pull request #1375
Opened 2022-09-29 05:29 UTC by ricardas-buc

Notes:

- Eventually this should follow onion styled architecture guidelines
- Current core module is too big, but it is lest as-is due to breaking changes and open PRs
- Existing unit tests required data duplication (configs,data,etc.) Eventually this has to be cleaned and refactored.

2022-09-30 19:14 UTC, ricardas-buc commented
Note: SonarQube shows unrelated to the PR changes errors, those already exist in branch.

2022-10-03 06:37 UTC, mloitm requested changes

2022-10-03 06:39 UTC, ricardas-buc commented on src/centralserver/admin-service/infra-api-rest/src/main/java/org/niis/xroad/centralserver/restapi/converter/model/InitialServerConfDtoConverter.java
> +public class InitialServerConfDtoConverter extends DtoConverter<InitialServerConfDto,
It could, but this PR is not refactoring code itself

2022-10-03 07:01 UTC, mloitm approved these changes

2022-10-03 07:13 UTC, merged