XRDDEV-2096 Improve documentation regarding Security Server <-> Information System communication
nordic-institute/X-Road pull request #1482
Opened 2023-01-05 13:20 UTC by andresrosenthal

https://nordic-institute.atlassian.net/browse/XRDDEV-2096

2023-01-08 07:42 UTC, petkivim reviewed
The document number and version history should be updated.

2023-01-08 07:42 UTC, petkivim commented on doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
> +  * [9.1 Communicating with security server as a service consumer](#91-communicating-with-security-server-as-a-service-consumer)
I would change this to "Communication with Service Consumer Information Systems" to make it more clear. Also, headings should be capitalized - all words are capitalized unless they are conjunctions, articles, or prepositions.

2023-01-08 07:42 UTC, petkivim commented on doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
> +  * [9.2 Communicating with security server as a service provider](#92-communicating-with-security-server-as-a-service-provider)
I would change this to "Communication with Service Provider Information Systems" to make it more clear. Also, headings should be capitalized - all words are capitalized unless they are conjunctions, articles, or prepositions.

2023-01-08 08:24 UTC, petkivim requested changes

2023-01-08 08:24 UTC, petkivim commented on doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
> +5.  In the view that opens, change the protocol (a.k.a. scheme) part in the Service URL to either **http://** or **https://**.
I would consider updating this part a little bit:

> 5. In the view that opens, change the protocol (a.k.a. scheme) part in the Service URL to either `http://` or `https://`.
> - HTTP – the service/adapter URL begins with `http://`.
> - HTTPS – the service/adapter URL begins with `https://`.
>    - If **Verify TLS certificate** checkbox is left unchecked it means that service provider information system's TLS certificate is not verified and is trusted by default.
 >   - If **Verify TLS certificate** checkbox is checked it means that service provider information system's TLS certificate is verified. In order to make the information system's TLS certificate trusted, it must be added into security server's **Information System TLS certificate** list (see section [9.3](https://github.com/nordic-institute/X-Road/blob/00c191c0670c231d295beb967826bcaa52bdae38/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#93-managing-information-system-tls-certificates)).
>    - When the service provider information system needs to verify the Security Server's internal TLS certificate, the certificate must be first exported and then imported into the service provider information system's truststore (see section [9.3](https://github.com/nordic-institute/X-Road/blob/00c191c0670c231d295beb967826bcaa52bdae38/doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md#93-managing-information-system-tls-certificates)).

2023-01-09 13:06 UTC, andresrosenthal commented
> The changes look good. The only thing that's missing is updating the document number and version history table.

Added

2023-01-09 14:29 UTC, petkivim approved these changes

2023-01-10 08:37 UTC, merged