fix(cs:api): Active session check
nordic-institute/X-Road pull request #1628
Opened 2023-04-24 06:55 UTC by ovidijusnortal

quick change to have consistent back button form details view

Refs: XRDDEV-2343

2023-04-25 07:30 UTC, ovidijusnortal commented
[rerun-ci]

2023-04-25 08:20 UTC, ovidijusnortal commented
[rerun-ci]

2023-04-27 08:23 UTC, andresrosenthal requested changes

2023-04-27 08:23 UTC, andresrosenthal commented on src/central-server/admin-service/ui/src/components/globalGroups/GlobalGroupMembers.vue
> +        <span data-test="subsystem">{{ item.client_id.subsystem_code }}</span></template>
I assume `</template>` got rearranged accidentally 🙃

2023-04-27 10:05 UTC, andresrosenthal approved these changes

2023-04-27 10:29 UTC, merged