feat: Caffeine based Api-Key caching
nordic-institute/X-Road pull request #1690
Opened 2023-05-31 17:00 UTC by ricardas-buc

Refs: XRDDEV-444

2023-06-01 06:07 UTC, ricardas-buc commented
[rerun-ci]

2023-06-01 06:50 UTC, raits requested changes
A few minor changes, but otherwise, the documentation looks good to me.

2023-06-01 06:50 UTC, raits commented on doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
> +API keys are cached in memory, which is typically not a problem in non-clustered central server configuration.
Let's write central server as Central Server.

2023-06-01 06:50 UTC, raits commented on doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
> +- **Option B:** Direct all REST API operations to the same security server node.
Let's change security server to Security Server here similar to what we do with the Central Server.

2023-06-01 06:50 UTC, raits commented on doc/Manuals/ug-cs_x-road_6_central_server_user_guide.md
> +- **Option B:** Direct all REST API operations to the same security server node.
This should probably be Central Server instead of Security Server.

2023-06-01 07:11 UTC, raits approved these changes
Documentation looks good to me.

2023-06-02 06:19 UTC, ovidijusnortal approved these changes

2023-06-02 06:28 UTC, merged