Xrddev 1050 e2etests keyscerts create
nordic-institute/X-Road pull request #815
Opened 2020-12-30 09:13 UTC by olliru

Added tests
XRDDEV-1050 create key and csr
XRDDEV-1399 delete csr

2020-12-30 14:21 UTC, Riippi requested changes

2020-12-30 14:21 UTC, Riippi commented on src/proxy-ui-api/frontend/tests/e2e/pages/tabs/keysTab.js
> +    //this.click('@yesButton');
Commented lines should be removed?
Also 3 more below this.

2020-12-30 14:21 UTC, Riippi commented on src/proxy-ui-api/frontend/tests/e2e/specs/ss-keyscerts-authsignkeys.js
> +    //addKeyWizardCSR.selectClient('REST-UI-TEST:GOV:0245437-2');
Commented lines should be removed?

2020-12-30 14:26 UTC, olliru commented on src/proxy-ui-api/frontend/tests/e2e/specs/ss-keyscerts-authsignkeys.js
> +    //addKeyWizardCSR.selectClient('REST-UI-TEST:GOV:0245437-2');
Yes this line should be removed

2021-03-04 13:19 UTC, closed without merging

2021-03-04 13:20 UTC, olliru commented
Changes merger as part of another PR