XRDDEV-1606 Central server frontend stub
nordic-institute/X-Road pull request #904
Opened 2021-03-09 13:41 UTC by Riippi

https://jira.niis.org/browse/XRDDEV-1606

Setup the central server frontend project

2021-03-11 15:07 UTC, TJaakkola requested changes
I think it wouldn't hurt to add a short description to each of the files. This is a good practise when writing vue-components but I think also files like shims-vue.d.ts, shims-tsx.d.ts, index.ts, main.ts could include a description. I think it would make traversing frontend code and getting to know to it easier at least for those who are not familiar with the project or aren't frontend oriented. 

Writing these descriptions should probably be a part of acceptance criteria. Maybe just add some description to those files I've mentioned above.

2021-03-11 16:37 UTC, Riippi commented on src/centralserver/admin-ui/src/store/types.ts
> +}
Moved this to global.ts

2021-03-11 16:37 UTC, Riippi commented on src/centralserver/admin-ui/src/plugins/vuetify.ts
> +        grey: '#9c9c9c',
Changed these to enum in global.ts

2021-03-12 06:30 UTC, TJaakkola approved these changes

2021-03-12 06:33 UTC, merged